---
crio_version: "v1.34"
crio_os: xUbuntu_22.04
kubernetes_version: "1.19"
crio_repo: 
crio_skopeo: false
crio_cni: false
cni_plugin_version: v1.8.0
cni_plugin_url: https://github.com/containernetworking/plugins/releases/download/{{ cni_plugin_version }}/cni-plugins-linux-arm64-{{ cni_plugin_version }}.tgz
