---
- hosts: localhost
  become: yes
  roles:
    - tools
- hosts: localhost
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - container.yaml
        - crio-ver
        - pod.yaml
