---
- hosts: remote
  become: yes
  roles:
    - tools
    - docker-ce
    - k3s
    - todo
- hosts: localhost
  tasks:
    - debug:
        msg: "Once your Kubernetes cluster is up, you can access the todo application at http://{{ inventory_hostname }}/todo/"
- hosts: vagrant
  tasks:
    - debug:
        msg: "Once your Kubernetes cluster is up, you can access the todo application at http://localhost:48080/todo/"
